[package]
name = "igneous-md"
description = "The simple and lightweight markdown viewer"
version = "0.1.3"
edition = "2021"
categories = ["gui", "development-tools"]
keywords = ["markdown", "gui", "markdown-viewer", "md"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/DOD-101/igneous-md"
authors = ["David Thievon"]

[features]
default = ["generate_config"]
generate_config = []


[dependencies]
chrono = { version = "0.4.38", features = ["clock"] }
clap = { version = "4.5.16", features = ["derive"] }
gtk = "0.18.1"
home = "0.5.9"
itertools = "0.13.0"
kuchikiki = "0.8.2"
log = "0.4.22"
markdown = "1.0.0-alpha.20"
open = "5.3.0"
rocket = "0.5.1"
rocket_ws = "0.1.1"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.134"
serde_urlencoded = "0.7.1"
simple_logger = "5.0.0"
toml = "0.8.19"
uuid = { version = "1.11.0", features = ["v4"] }
webkit2gtk = "2.0.1"
