[package]
name = "igneous-md"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
home = "0.5.9"
markdown = "1.0.0-alpha.20"
open = "5.3.0"
rouille = "3.6.2"
serde = { version = "1.0.208", features = ["derive"] }
serde_urlencoded = "0.7.1"
toml = "0.8.19"
web-view = "0.7.3"
