// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Possible messages sent by the client
 */
export type ClientMsg = { "t": "ChangeCss", "c": { 
/**
 * Which stylesheet to get
 */
index: number, 
/**
 * If the change is relative to the current css index
 */
relative: boolean, } } | { "t": "RequestExport" } | { "t": "Redirect", "c": { 
/**
 * Where the redirect is headed
 */
path: string, } } | { "t": "RedirectDefault" } | { "t": "CheckServer" };
