// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Possible messages sent by the server
 */
export type ServerMsg = { "t": "CssUpdate", "c": { 
/**
 * Css content
 */
css: string, } } | { "t": "HtmlUpdate", "c": { 
/**
 * Html content
 */
html: string, } } | { "t": "Export", "c": { 
/**
 * The path to export to
 */
path: string, } } | { "t": "Exit", "c": { 
/**
 * If the exit is due to an error
 */
error: boolean, } } | { "t": "Success" } | { "t": "Error", "c": { 
/**
 * Message describing in human-readable format the issue
 */
msg: string, } };
