use std::fmt::Display;

use gtk4::{
    Application, ApplicationWindow, PAPER_NAME_A4, PageSetup, PaperSize, PrintSettings, gio, glib,
    prelude::*,
};
use webkit6::{
    CacheModel, PrintOperation, Settings, URISchemeRequest, UserContentManager, WebContext,
    WebView, prelude::*,
};

/// index.html generated by the build script
pub static HTML: &str = include_str!(concat!(env!("OUT_DIR"), "/index.html"));

/// Struct representing the igneous-md markdown viewer.
#[derive(Debug)]
pub struct Viewer<'a> {
    /// Address the webview will have set as `window.location`
    addr: Address<'a>,
    /// If the viewer should run in headless-mode (aka. not be seen by users)
    headless: bool,
    /// Sender used to signal the result of an export operation to the rest of the application
    ///
    /// If [None] the viewer will not signal anyone.
    export_signal: Option<std::sync::mpsc::Sender<ExportResult>>,
}

/// Result of an export operation, signaled by the [Viewer] to the rest of the application.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExportResult {
    /// The export completed successfully
    Success,
    /// The export failed
    Failure,
}

impl<'a> Viewer<'a> {
    /// Create a new [Viewer]
    pub fn new(
        addr: Address<'a>,
        headless: bool,
        export_signal: Option<std::sync::mpsc::Sender<ExportResult>>,
    ) -> Self {
        Viewer {
            addr,
            headless,
            export_signal,
        }
    }

    /// Start the viewer
    pub fn start(&self) {
        let app = Application::builder().application_id(self.app_id()).build();

        let addr = self.addr.to_string();
        let headless = self.headless;
        let export_signal = self.export_signal.clone();
        app.connect_activate(move |app| {
            Self::build_ui(&addr, headless, app, export_signal.clone());
        });

        app.run_with_args::<&str>(&[]);
    }

    /// Unique GTK application id derived from the viewer's address.
    ///
    /// GTK [Application]s are single-instance per id (enforced over D-Bus), so
    /// every viewer needs its own id or the second one would just "activate" the
    /// first, resulting in all windows showing the same document.
    fn app_id(&self) -> String {
        use std::hash::{DefaultHasher, Hash, Hasher};

        let mut hasher = DefaultHasher::new();
        self.addr.hash(&mut hasher);
        format!("dod.igneous-md.viewer.id_{}", hasher.finish())
    }

    /// Build the actual GTK UI
    fn build_ui(
        addr: &str,
        headless: bool,
        app: &Application,
        export_signal: Option<std::sync::mpsc::Sender<ExportResult>>,
    ) {
        let window = ApplicationWindow::builder()
            .application(app)
            .title("igneous-md viewer")
            .visible(!headless)
            .build();

        let context = WebContext::new();
        context.set_cache_model(CacheModel::DocumentBrowser);
        // TODO: Not sure this will behave properly with relative paths in all cases. Needs further
        // testing.
        context.register_uri_scheme("asset", |req: &URISchemeRequest| {
            let uri = req.uri().unwrap();
            let path = uri.strip_prefix("asset://").unwrap();

            match std::fs::read(path) {
                Ok(bytes) => {
                    let mime = mime_guess::from_path(path)
                        .first_or_octet_stream()
                        .to_string();
                    let stream = gio::MemoryInputStream::from_bytes(&glib::Bytes::from(&bytes));
                    req.finish(&stream, bytes.len() as i64, Some(&mime));
                }
                Err(e) => {
                    req.finish_error(&mut glib::Error::new(
                        gio::IOErrorEnum::NotFound,
                        &e.to_string(),
                    ));
                }
            }
        });

        let content = UserContentManager::new();
        content.register_script_message_handler("exportPDF", None);

        let view = WebView::builder()
            .web_context(&context)
            .user_content_manager(&content)
            .visible(!headless)
            .settings(
                &Settings::builder()
                    .print_backgrounds(true)
                    .enable_developer_extras(true)
                    .build(),
            )
            .build();
        view.show();

        let web_view_clone = view.clone();
        content.connect_script_message_received(None, move |_manager, value| {
            Self::to_pdf_handler(&web_view_clone, &value.to_string(), export_signal.clone());
        });

        window.set_child(Some(&view));

        if headless {
            gtk4::prelude::WidgetExt::realize(&window);
        } else {
            window.present();
        }

        view.load_html(HTML, Some(addr));
    }

    /// Export current webview content (the markdown) to pdf
    fn to_pdf_handler(
        web_view: &WebView,
        path: &str,
        export_signal: Option<std::sync::mpsc::Sender<ExportResult>>,
    ) {
        let print_settings = PrintSettings::new();

        print_settings.set_printer("Print to File");
        print_settings.set("output-uri", Some(&format!("file://{path}")));
        print_settings.set_use_color(true);

        let page_setup = PageSetup::new();
        page_setup.set_paper_size(&PaperSize::new(Some(PAPER_NAME_A4)));

        page_setup.set_left_margin(0_f64, gtk4::Unit::Points);
        page_setup.set_right_margin(0_f64, gtk4::Unit::Points);
        page_setup.set_top_margin(0_f64, gtk4::Unit::Points);
        page_setup.set_bottom_margin(0_f64, gtk4::Unit::Points);

        let print_op = PrintOperation::builder()
            .print_settings(&print_settings)
            .page_setup(&page_setup)
            .web_view(web_view)
            .build();

        let path_clone = path.to_owned();
        let finished_signal = export_signal.clone();
        print_op.connect_finished(move |_| {
            println!("PDF exported successfully to {}!", path_clone);

            if let Some(sender) = &finished_signal {
                let _ = sender.send(ExportResult::Success);
            }
        });

        print_op.connect_failed(move |_, error| {
            eprintln!("PDF export failed: {error}");

            if let Some(sender) = &export_signal {
                let _ = sender.send(ExportResult::Failure);
            }
        });

        print_op.print();
    }
}

#[derive(Debug, Default, Clone, Copy, Hash)]
pub struct Address<'a> {
    host: &'a str,
    port: u16,
    update_rate: u64,
    css: Option<&'a str>,
    path: &'a str,
    export: Option<&'a str>,
}

impl<'a> Address<'a> {
    pub fn new(
        host: &'a str,
        port: u16,
        update_rate: u64,
        css: Option<&'a str>,
        path: &'a str,
        export: Option<&'a str>,
    ) -> Self {
        Self {
            host,
            port,
            update_rate,
            css,
            path,
            export,
        }
    }
}

impl Display for Address<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "http://{}:{}/?update_rate={}&path={}{}{}",
            self.host,
            self.port,
            self.update_rate,
            self.path,
            self.css.map(|s| format!("&css={}", s)).unwrap_or_default(),
            self.export
                .map(|s| format!("&export={}", s))
                .unwrap_or_default(),
        )
    }
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn app_id_is_unique_per_document() {
        let mk = |path: &str| {
            Viewer::new(
                Address::new("localhost", 8080, 1000, None, path, None),
                false,
                None,
            )
            .app_id()
        };

        assert_ne!(mk("/a.md"), mk("/b.md"));
        assert_eq!(mk("/a.md"), mk("/a.md"));
        assert_eq!(mk("a.md"), mk("a.md"));
    }

    #[test]
    fn app_id_is_valid_dbus_name() {
        let viewer = Viewer::new(
            Address::new("localhost", 8080, 1000, None, "/home/user/notes.md", None),
            false,
            None,
        );
        let id = viewer.app_id();

        assert!(id.len() <= 255);
        assert!(id.contains('.'));
        for element in id.split('.') {
            assert!(!element.is_empty());
            assert!(
                element.starts_with(|c: char| c.is_ascii_alphabetic() || c == '_'),
                "invalid element {element:?} in {id:?}"
            );
            assert!(
                element
                    .chars()
                    .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
            );
        }
    }
}
