use std::fmt::Display;

use gtk4::{
    gio, glib, prelude::*, Application, ApplicationWindow, PageSetup, PaperSize, PrintSettings,
    PAPER_NAME_A4,
};
use webkit6::{
    prelude::*, CacheModel, PrintOperation, Settings, URISchemeRequest, UserContentManager,
    WebContext, WebView,
};

/// index.html generated by the build script
pub static HTML: &str = include_str!(concat!(env!("OUT_DIR"), "/index.html"));

/// Struct representing the igneous-md markdown viewer.
#[derive(Debug)]
pub struct Viewer<'a> {
    /// Address the webview will have set as `window.location`
    addr: Address<'a>,
    /// If the viewer should run in headless-mode (aka. not be seen by users)
    headless: bool,
}

const APP_ID: &str = "dod.igneous-md.viewer";

impl<'a> Viewer<'a> {
    /// Create a new [Viewer]
    pub fn new(addr: Address<'a>, headless: bool) -> Self {
        Viewer { addr, headless }
    }

    /// Start the viewer
    pub fn start(&self) {
        let app = Application::builder().application_id(APP_ID).build();

        let addr = self.addr.to_string();
        let headless = self.headless;
        app.connect_activate(move |app| {
            Self::build_ui(&addr, headless, app);
        });

        app.run_with_args::<&str>(&[]);
    }

    /// Build the actual GTK UI
    fn build_ui(addr: &str, headless: bool, app: &Application) {
        let window = ApplicationWindow::builder()
            .application(app)
            .title("igneous-md viewer")
            .visible(!headless)
            .build();

        let context = WebContext::default().unwrap();
        context.set_cache_model(CacheModel::DocumentBrowser);
        // TODO: Not sure this will behave properly with relative paths in all cases. Needs further
        // testing.
        context.register_uri_scheme("asset", |req: &URISchemeRequest| {
            let uri = req.uri().unwrap();
            let path = uri.strip_prefix("asset://").unwrap();

            match std::fs::read(path) {
                Ok(bytes) => {
                    let mime = mime_guess::from_path(path)
                        .first_or_octet_stream()
                        .to_string();
                    let stream = gio::MemoryInputStream::from_bytes(&glib::Bytes::from(&bytes));
                    req.finish(&stream, bytes.len() as i64, Some(&mime));
                }
                Err(e) => {
                    req.finish_error(&mut glib::Error::new(
                        gio::IOErrorEnum::NotFound,
                        &e.to_string(),
                    ));
                }
            }
        });

        let content = UserContentManager::new();
        content.register_script_message_handler("exportPDF", None);

        let view = WebView::builder()
            .web_context(&context)
            .user_content_manager(&content)
            .settings(
                &Settings::builder()
                    .print_backgrounds(true)
                    .enable_developer_extras(true)
                    .build(),
            )
            .build();
        view.show();

        let web_view_clone = view.clone();
        content.connect_script_message_received(None, move |_manager, value| {
            Self::to_pdf_handler(&web_view_clone, &value.to_string());
        });

        window.set_child(Some(&view));
        window.present();
        view.load_html(HTML, Some(addr));
    }

    /// Export current webview content (the markdown) to pdf
    fn to_pdf_handler(web_view: &WebView, path: &str) {
        let print_settings = PrintSettings::new();

        print_settings.set_printer("Print to File");
        print_settings.set("output-uri", Some(&format!("file://{path}")));
        print_settings.set_use_color(true);

        let page_setup = PageSetup::new();
        page_setup.set_paper_size(&PaperSize::new(Some(PAPER_NAME_A4)));

        page_setup.set_left_margin(0_f64, gtk4::Unit::Points);
        page_setup.set_right_margin(0_f64, gtk4::Unit::Points);
        page_setup.set_top_margin(0_f64, gtk4::Unit::Points);
        page_setup.set_bottom_margin(0_f64, gtk4::Unit::Points);

        let print_op = PrintOperation::builder()
            .print_settings(&print_settings)
            .page_setup(&page_setup)
            .web_view(web_view)
            .build();

        let path_clone = path.to_owned();
        print_op.connect_finished(move |_| {
            println!("PDF exported successfully to {}!", path_clone);
        });

        print_op.connect_failed(|_, error| {
            eprintln!("PDF export failed: {error}");
        });

        print_op.print();
    }
}

#[derive(Debug, Default, Clone, Copy)]
pub struct Address<'a> {
    host: &'a str,
    port: u16,
    update_rate: u64,
    css: Option<&'a str>,
    path: &'a str,
}

impl<'a> Address<'a> {
    pub fn new(
        host: &'a str,
        port: u16,
        update_rate: u64,
        css: Option<&'a str>,
        path: &'a str,
    ) -> Self {
        Self {
            host,
            port,
            update_rate,
            css,
            path,
        }
    }
}

impl Display for Address<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "http://{}:{}/?update_rate={}&path={}{}",
            self.host,
            self.port,
            self.update_rate,
            self.path,
            self.css.map(|s| format!("&css={}", s)).unwrap_or_default(),
        )
    }
}
