name: Linux Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.0.4]
        rust: [stable]

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

    - name: Install dependencies
      run: |
          if [ "${matrix.os}" == "ubuntu-latest" ]; then
            sudo apt update
            sudo apt install -y libwebkit2gtk-4.0-dev
          fi
    
